---

- block:

  - name: Pull smsgw project
    git:
      repo: https://github.com/VojtechBartos/smsgw.git
      dest: /usr/src/smsgw/
      version: master
      accept_hostkey: True
      force: yes

  - name: Creating env file
    template:
      src: ../../../../.env.sample
      dest: /usr/src/smsgw/.env

  - name: Pulling images
    command: docker-compose pull
    args:
      chdir: /usr/src/smsgw/
    notify:
      - Docker compose up

  become: yes
  become_user: root
