services:
  - rabbitmq

language: python

python:
  - 2.7

env:
  global:
    - TESTING=1
    - DEBUG=1
    - DATABASE_HOST="localhost"
    - DATABASE_NAME="smsgw_test"
    - DATABASE_USERNAME="travis"
    - DATABASE_PASSWORD=""

install: "pip install -r requirements.txt"

before_script:
  - mysql -e 'create database smsgw_test;'

script: nosetests
