---

- block:

  # TODO(vojta) install it manually
  - name: Install Docker
    shell: curl -fsSL https://get.docker.com/ | sh

  - name: Install docker-compose and docker-py
    pip:
      name: "{{ item }}"
    with_items:
      - docker-compose==1.7.0
      - docker-py==1.8.0 # to be able to manage docker via ansible

  become: yes
  become_user: root
