---
- hosts: all
  sudo: true
  tasks:
    - name: upgrade all packages to latest version and update cache
      apt: upgrade=dist update_cache=yes

    - name: installing general packages
      apt: name={{ item }}
      with_items:
        - sendmail-bin
        - sendmail
        - g++
        - make
        - vim
        - git-core
        - cmake

    - name: install nginx
      apt: name=nginx

    - name: install python
      apt: name={{ item }}
      with_items:
        - python
        - python-dev
        - python-setuptools
        - python-virtualenv
        - python-software-properties

    - name: install supervisor
      apt: name=supervisor

    # mariadb
    - apt_key: keyserver=keyserver.ubuntu.com id=0xcbcb082a1bb943db
    - apt_repository: repo='deb http://mirror.vpsfree.cz/mariadb/repo/5.5/debian wheezy main'
    - apt: update_cache=yes
    - apt: name=mariadb-server

    # gammu
    - git: repo=https://github.com/gammu/gammu.git
           dest=/tmp/gammu
           version=1.34.0
    - shell: ./configure chdir=/tmp/gammu
    - shell: make chdir=/tmp/gammu
    - shell: make install chdir=/tmp/gammu

