---
- hosts: all
  sudo: true
  tasks:
    - name: upgrade all packages to latest version and update cache
      apt: upgrade=dist update_cache=yes

    - include: tasks/common.yml
    - include: tasks/nginx.yml
    - include: tasks/rabbitmq.yml
    - include: tasks/supervisor.yml
    - include: tasks/mariadb.yml
    - include: tasks/python.yml
    - include: tasks/gammu.yml
